# Generated by Django 6.0.2 on 2026-02-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.CreateModel(
            name='AmountReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_received', to='App.user')),
            ],
        ),
    ]
